### ISSUE TITLE
「ハンズオン環境のダウンロード」について

### ISSUE THREAD

**Issue by AFtsukuba** [chemo-wakate/tutorial-6th#18]
第6回ケモインフォマティクス入門講座の準備でお世話になっております。

Windows10(64bit)環境でDockerとgitのインストールまでは手順通りに終了しました。
git clone https://github.com/chemo-wakate/tutorial-6th.gitを実行後
cd tutorial-6th
docker pull chemowakate/tutorial-6th
を実行すると以下のエラーでハンズオン環境がダウンロードできませんでした。
Using default tag: latest
latest: Pulling from chemowakate/tutorial-6th
image operating system "linux" cannot be used on this platform

対処方法についてご教示頂けますでしょうか。よろしくお願いいたします。

**Comment by kubor** [comment]
Dockerを動かしている仮想マシンの設定で同様のエラーが出ることがあるようです。

https://qiita.com/pluto134340/items/eb4e19421a7b01a1a276#docker%E3%81%AE%E3%83%90%E3%83%BC%E3%82%B8%E3%83%A7%E3%83%B3%E7%A2%BA%E8%AA%8D

こちらの"Dockerのバージョン確認"をご確認の上、設定を試してみてください。

@AFtsukuba

**Comment by AFtsukuba** [comment]
ご回答ありがとうございます。Serverの設定でOS/Arch: windows/amd64だったため、変更してダウンロードはうまくいきました。ありがとうございます。

ただ、「sh ./run_jupyter.sh 入力時のエラー #19」に類似したエラーで止まっております。内容は♯19のコメントに追記させて頂きます。
