### ISSUE TITLE
sh ./run_jupyter.sh 入力時のエラー

### ISSUE THREAD

**Issue by hkaneko1985** [chemo-wakate/tutorial-6th#19]
ハンズオン環境のダウンロードをしたあとに、
sh ./run_jupyter.sh
と入力したら、こんなことを言われてしまいました。
![snapcrab_2017-9-28_15-57-54_no-00](https://user-images.githubusercontent.com/31059982/30953410-bbcef572-a466-11e7-8f76-b24da0afa0b0.png)
どう対応すればよろしいでしょうか？
Windows 10 Pro です。

**Comment by hkaneko1985** [comment]
ちなみに、
cat ./run_jupyter.sh
と入力するとこうなります。
![snapcrab_2017-9-28_16-2-13_no-00](https://user-images.githubusercontent.com/31059982/30953430-dcd7ca96-a466-11e7-858c-8b7218f1e1ae.png)

**Comment by AFtsukuba** [comment]
Windows10(64bit)環境の当方の場合のエラーについて追記させてください。まず、
sh ./run_jupyter.sh
the input device is not a TTY.  If you are using mintty, try prefixing the command with 'winpty'
とエラーがでます。

その後、winpty sh ./run_jupyter.shを実行すると以下のエラーが出ます。（XXXはログイン名です）
C:\Program Files\Docker\Docker\Resources\bin\docker.exe: Error response from dae
mon: invalid bind mount spec "/C/Users/XXX/tutorial-6th;C:\\Program Files\\
Git\\home\\jovyan\\chemo": invalid volume specification: '/C/Users/XXX/tuto
rial-6th;C:\Program Files\Git\home\jovyan\chemo': invalid mount config for type
"bind": invalid mount path: '\Program Files\Git\home\jovyan\chemo' mount path mu
st be absolute.
See 'C:\Program Files\Docker\Docker\Resources\bin\docker.exe run --help'.

解決方法を模索中です。

**Comment by hkaneko1985** [comment]
gitを再インストールしましたら、AFtsukubaさんと同じエラーになりました。

**Comment by yamasakih** [comment]
@AFtsukuba @hkaneko1985 

docker run --rm -t chemowakate/tutorial-6th

のみ実行したらどうなりますか？

**Comment by AFtsukuba** [comment]
結果は以下の通りです。

$ docker run --rm -t chemowakate/tutorial-6th
Execute the command: jupyter notebook
[I 07:55:28.012 NotebookApp] Writing notebook server cookie secret to /home/jovyan/.local/share/jupyter/runtime/notebook_cookie_secret
[W 07:55:28.042 NotebookApp] WARNING: The notebook server is listening on all IP addresses and not using encryption. This is not recommended.
[I 07:55:28.082 NotebookApp] JupyterLab alpha preview extension loaded from /opt/conda/lib/python3.6/site-packages/jupyterlab
JupyterLab v0.27.0
Known labextensions:
[I 07:55:28.085 NotebookApp] Running the core application with no additional extensions or settings
[I 07:55:28.089 NotebookApp] Serving notebooks from local directory: /home/jovyan
[I 07:55:28.089 NotebookApp] 0 active kernels
[I 07:55:28.090 NotebookApp] The Jupyter Notebook is running at: http://[all ip addresses on your system]:8888/?token=33fecc（省略）
[I 07:55:28.090 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 07:55:28.090 NotebookApp]

    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8888/?token=33fecc（省略）

**Comment by hkaneko1985** [comment]
私も同じような結果です。

$ docker run --rm -t chemowakate/tutorial-6th
Execute the command: jupyter notebook
[I 07:59:21.464 NotebookApp] Writing notebook server cookie secret to /home/jovyan/.local/share/jupyter/runtime/notebook_cookie_secret
[W 07:59:21.484 NotebookApp] WARNING: The notebook server is listening on all IP addresses and not using encryption. This is not recommended.
[I 07:59:21.515 NotebookApp] JupyterLab alpha preview extension loaded from /opt/conda/lib/python3.6/site-packages/jupyterlab
JupyterLab v0.27.0
Known labextensions:
[I 07:59:21.521 NotebookApp] Running the core application with no additional extensions or settings
[I 07:59:21.526 NotebookApp] Serving notebooks from local directory: /home/jovyan
[I 07:59:21.526 NotebookApp] 0 active kernels
[I 07:59:21.527 NotebookApp] The Jupyter Notebook is running at: http://[all ip addresses on your system]:8888/?token=c8beaa4d69330a74c19f22b1b3bd64743ab842f8b5c45f6e
[I 07:59:21.527 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 07:59:21.528 NotebookApp]

    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8888/?token=c8beaa4d69330a74c19f22b1b3bd64743ab842f8b5c45f6e

**Comment by yamasakih** [comment]
>the input device is not a TTY. If you are using mintty, try prefixing the command with 'winpty'

というエラーに関する記事を見つけました。

https://7me.oji.0j0.jp/2016/docker-for-windows.html

git bashなどのターミナルを利用している場合MINTTYのようです。
Windowsに標準でインストールされているTerminalや
インストールしたDockerによっては同時にインストールされるDockerQuickTerminalで
同様の作業をしてみてください。

DockerQuickTerminalがない場合無理にインストールせずその旨を伝えください。

@AFtsukuba @hkaneko1985

**Comment by yamasakih** [comment]
あ、失礼しました。

@AFtsukuba さんはすでに
```
winpty sh ./run_jupyter.sh
```
を実行されていますね。
インストールされているTerminalの代わりにwinpty sh ./run_jupyter.shでも構いませんね。

**Comment by yamasakih** [comment]
同様のエラーを再現して、解決策をみつけました。
おまたせしてすいませんでした。

cd tutorial-6th
pwd 

で表示されるディレクトリがを例えば/c/Users/yamasakih/tutorial-6thでしたら

```
winpty docker run --rm -p 8888:8888 -v //c/Users/yamasakih/tutorial-6th:/home/jovyan/chemo -t chemowakate/tutorial-6th
```

と実行していただけますでしょうか？

-vの直後は最初だけスラッシュ二個です。


これを実行しても起こるエラーとして２つ考えられます
1. **ディレクトリに空白がある**
/c/Users/yamasaki hiroyuki/tutorial-6th
のように空白があるとうまく起動しないことを検証しました。
その場合は空白がないディレクトリで行ってみて下さい。

1. **8888のポートですでに別の仮想環境が動いている**
試行錯誤で色々試されて、別の仮想環境が動いているなら

```
Bind for 0.0.0:8888 failed: port is already allocated.
```

と一番最後に表示されるエラーが起きます。

その場合は

```
winpty docker run --rm -p 8888:3000 -v //c/Users/yamasakih/tutorial-6th:/home/jovyan/chemo -t chemowakate/tutorial-6th
```

というふうに後半の8888を3000に変えてみて下さい。

よろしくお願いします。

@hkaneko1985 @AFtsukuba

**Comment by AFtsukuba** [comment]
@yamasakih さま、ありがとうございます！PCの再起動や試行錯誤を行った結果、GitBash上での
winpty docker run --rm -p 8888:8888 -v //c/Users/XXX/tutorial-6th:/home/jovyan/chemo -t chemowakate/tutorial-6th
のコマンドで以下の表示が現れました。（XXXはユーザー名）

Execute the command: jupyter notebook
[I 01:15:09.016 NotebookApp] Writing notebook server cookie secret to /home/jovyan/.local/share/jupyter/runtime/notebook_cookie_secret
[W 01:15:09.071 NotebookApp] WARNING: The notebook server is listening on all IP addresses and not using encryption. This is not recommended.
[I 01:15:09.134 NotebookApp] JupyterLab alpha preview extension loaded from /opt/conda/lib/python3.6/site-packages/jupyterlab
JupyterLab v0.27.0
Known labextensions:
[I 01:15:09.139 NotebookApp] Running the core application with no additional extensions or settings
[I 01:15:09.147 NotebookApp] Serving notebooks from local directory: /home/jovyan
[I 01:15:09.147 NotebookApp] 0 active kernels
[I 01:15:09.147 NotebookApp] The Jupyter Notebook is running at: http://[all ipaddresses on your system]:8888/?token=c1c7ca94d4ae562921d50f1d537fdb63bc7f13bdfc84b765
[I 01:15:09.147 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 01:15:09.149 NotebookApp]

    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8888/?token=c1c7ca94d4ae562921d50f1d537fdb63bc7f13bdfc84b765

ブラウザでhttp://localhost:8888/?token=c1c7ca94d4ae562921d50f1d537fdb63bc7f13bdfc84b765　にアクセスするとhttps://github.com/chemo-wakate/tutorial-6th/blob/master/README.mdの最終画面と同様にchemo/ の中にリポジトリの内容が入っているのを確認できました。

これで無事に明日の準備ができたかと思います。
解決に、お時間を取らせてしまい失礼しました。

**Comment by yamasakih** [comment]
@AFtsukuba さんうまく起動して良かったです。

当日はさらに-itオプションを加えた

```
winpty docker run --rm -it -p 8888:8888 -v //c/Users/yamasakih/tutorial-6th:/home/jovyan/chemo -t chemowakate/tutorial-6th
```

をお使いいただけるとよいと思います。
よろしくお願いします。
