### ISSUE TITLE
sh ./run_jupyter.shのエラー

### ISSUE THREAD

**Issue by Orgchem** [chemo-wakate/tutorial-6th#22]
全くの素人質問で申し訳ありません。
手順に従い、ハンズオン環境のDLまで行いましたが、
sh ./run_jupyter.sh
を入力すると、下記のようにエラーで進めません。

PS C:\Users\Masahiro> sh ./run_jupyter.sh
sh : 用語 'sh' は、コマンドレット、関数、スクリプト ファイル、または操作可能なプログラムの名前として認識されません。名前が正しく記述されていることを確認し、パスが含まれている場合はそのパスが正しいことを確認してから、再試行してください。
発生場所 行:1 文字:1
+ sh ./run_jupyter.sh
+ ~~
    + CategoryInfo          : ObjectNotFound: (sh:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by yamasakih** [comment]
質問ありがとうございます。

お使いのパソコンのOS (Windows 64bitなど)

```
sh ./run_jupyter.sh
```

を実行したソフト(コマンドプロンプトなど)を教えていただけますでしょうか？

@Orgchem

**Comment by Orgchem** [comment]
Windows 10 Pro 64bit です。

下記をインストールして、
Docker CE　Version 17.06.2-ce-win27 (13194)
Channel: stable

Windows PowerShellにて、下記を実行してインストールの確認はできました。
PS C:\Users\Masahiro> docker run hello-world

Hello from Docker!
This message shows that your installation appears to be working correctly.

To generate this message, Docker took the following steps:
 1. The Docker client contacted the Docker daemon.
 2. The Docker daemon pulled the "hello-world" image from the Docker Hub.
 3. The Docker daemon created a new container from that image which runs the
    executable that produces the output you are currently reading.
 4. The Docker daemon streamed that output to the Docker client, which sent it
    to your terminal.

To try something more ambitious, you can run an Ubuntu container with:
 $ docker run -it ubuntu bash

Share images, automate workflows, and more with a free Docker ID:
 https://cloud.docker.com/

For more examples and ideas, visit:
 https://docs.docker.com/engine/userguide/

さらに、gitをインストールした後に、Windows PowerShellで下記を実行し、
講義資料のインストールも終わっています。
git clone https://github.com/chemo-wakate/tutorial-6th.git
最後の「ダウンロードしたDockerコンテナで講義資料を表示できることを確認します」
のところで、Windows PowerShellで下記を実行したところ、エラーが出てしまっています。

PS C:\Users\Masahiro> sh ./run_jupyter.sh
sh : 用語 'sh' は、コマンドレット、関数、スクリプト ファイル、または操作可能なプログラムの名前として認識されません。名
前が正しく記述されていることを確認し、パスが含まれている場合はそのパスが正しいことを確認してから、再試行してください。
発生場所 行:1 文字:1
+ sh ./run_jupyter.sh
+ ~~
    + CategoryInfo          : ObjectNotFound: (sh:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by yamasakih** [comment]
詳細なご返答ありがとうございます！

```
sh
```

とだけ打っても同様のエラーが出ますかね？

その場合はお手数ですがrun_jupyter.shの中のコマンドを一度直接打ちましょう。

cd tutorial-6th
pwd
で表示されるディレクトリがを例えば/c/Users/yamasakih/tutorial-6thでしたら

```
docker run --rm -p 8888:8888 -v //c/Users/yamasakih/tutorial-6th:/home/jovyan/chemo -t chemowakate/tutorial-6th
```

と実行してみてください。
#19 の最後に書かれているものからwinptyを抜いたものです。

@Orgchem

**Comment by Orgchem** [comment]
ありがとうございました！
JupyterのURLにアクセスして、chemoのフォルダがありました。
大丈夫そうです。これから2限の講義なので、
また何かありましたら、よろしくお願いします。
