### ISSUE TITLE
cannot run "sh" in Windows

### ISSUE THREAD

**Issue by gjuhasz** [chemo-wakate/tutorial-6th#23]
英語ですが失礼します。
My system is a Win10 (64bit), Docker installed and could download Docker image.
However I should run Jupiter: "sh" is not available in Windows, and "bash" (Ubuntu bash for Windows) cannot run docker itself.
Can I run the jupyter server "docker run --rm -t chemowakate/tutorial-6th" from the library of tutorial or something similar?

**Comment by yamasakih** [comment]
Hello,

Let me check that can you use 'docker' command in your terminal?

If you want to try, please command like this:

```
docker -v
```

In my PC, return like this:
```
Docker version 17.03.1-ce, build c6d412e
```

How about this?

**Comment by gjuhasz** [comment]
In my pc it is 
`Docker version 17.06.2-ce, build cec0b72`

**Comment by kubor** [comment]
Hi.

I think you executed these commands on `cmd.exe` or `PowerShell`. So, plz try a below command on your environment.  
`%cd%` will be replaced by your current working directory.

```
docker run --rm -it -p 8888:8888 -v %cd%:/home/jovyan/chemo chemowakate/tutorial-6th
```

@gjuhasz

**Comment by gjuhasz** [comment]
Thanks for the help, yes, I run my commands from PowerShell
Sorry, for some reason Docker stopped responding (doesn't run anything, just hangs up). I think I have to reinstall everything.

**Comment by gjuhasz** [comment]
Thanks, it seems I had some problem with the installation or setup. The command like solution worked perfectly and started Jupyter as expected.
